## Task 1

In [2]:
import numpy as np

arr = list(map(int, input().split()))
array = np.array(arr, dtype='float')
print(np.flip(array))


[-10.  -8.   4.   3.   2.   1.]


## Task 2

In [9]:
arr = list(map(int, input().split()))
array = np.array(arr)
print(array.reshape(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Task 3

In [15]:
n, m = map(int, input().split())
print(np.eye(n, m))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Task 4

In [19]:
n, m = map(int, input().split())
arr1 = []
arr2 = []
for i in range(n):
    arr1.append(list(map(int, input().split())))

for i in range(n):
    arr2.append(list(map(int, input().split())))

A = np.array(arr1)
B = np.array(arr2)

print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A ** B)

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Task 5

In [21]:
n , m = map(int, input().split())
arr = []
for i in range(n):
    arr.append(list(map(int, input().split())))

matrix = np.array(arr)
print(matrix.transpose())
print(matrix.flatten())

[[1 3]
 [2 4]]
[1 2 3 4]
